### ISSUE TITLE
euclidean distance on 512 points 

### ISSUE THREAD

**Issue by tomriddle54** [droyed/eucl_dist#3]
Hello @droyed 
I have face encodings 512 points for one face I want to calculate euclidean distance of them using this code any idea?

**Comment by droyed** [comment]
> Hello @droyed
> I have face encodings 512 points for one face I want to calculate euclidean distance of them using this code any idea?

This is no different from [`SciPy's version`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.spatial.distance.cdist.html). So, go through the docs there and then figure out how to formulate your problem accordingly.
